// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlM3lJMg52LjLHNzSz6fjPyo1GFf9_VAQ',
    appId: '1:712792591959:web:0c246d5c21e0efea3cdd12',
    messagingSenderId: '712792591959',
    projectId: 'todo-list-60ce7',
    authDomain: 'todo-list-60ce7.firebaseapp.com',
    storageBucket: 'todo-list-60ce7.appspot.com',
    measurementId: 'G-M7XXH5S1YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_LihdUDNgBzaohLNIxAN0IQHH7IRCZxE',
    appId: '1:712792591959:android:0cc92bb4682a20db3cdd12',
    messagingSenderId: '712792591959',
    projectId: 'todo-list-60ce7',
    storageBucket: 'todo-list-60ce7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX97AM_-uv2Za_6Bnx9A7qQcDvaXMWI2w',
    appId: '1:712792591959:ios:32e24cb9e454b8ec3cdd12',
    messagingSenderId: '712792591959',
    projectId: 'todo-list-60ce7',
    storageBucket: 'todo-list-60ce7.appspot.com',
    iosClientId: '712792591959-np9tct25rsi1e9vb736cf4ocvroq0m79.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX97AM_-uv2Za_6Bnx9A7qQcDvaXMWI2w',
    appId: '1:712792591959:ios:a729bb6dad3f67bb3cdd12',
    messagingSenderId: '712792591959',
    projectId: 'todo-list-60ce7',
    storageBucket: 'todo-list-60ce7.appspot.com',
    iosClientId: '712792591959-n69l4j3pmeb7jlnaoat8a9o225dg8csm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
